import { mkdirSync, writeFileSync } from 'node:fs';
import { randomBytes, scryptSync, createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { demoGames } from './demo.js';

const root = fileURLToPath(new URL('../', import.meta.url));
export const remoteUrl = () => process.env.DATABASE_URL || process.env.POSTGRES_URL;
export const needsDatabase = () => !!process.env.VERCEL && !remoteUrl();
export class ConfigurationError extends Error {}
const hashToken = token => createHash('sha256').update(token).digest('hex');

export function postgresQuery(sql) {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

export async function initializeDatabase(db) {
  const id = db.kind === 'postgres' ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  await db.query(`CREATE TABLE IF NOT EXISTS games (id ${id}, body TEXT NOT NULL)`);
  await db.query('CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)');
  await db.query('CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, expires BIGINT NOT NULL, auth_hash TEXT NOT NULL)');
  await db.query('CREATE TABLE IF NOT EXISTS login_attempts (ip TEXT PRIMARY KEY, count INTEGER NOT NULL, expires BIGINT NOT NULL)');
  const seeded = await db.query("SELECT value FROM settings WHERE key='seeded'");
  if (!seeded.rows.length) {
    for (const { id: ignored, ...game } of demoGames) await db.query('INSERT INTO games(body) VALUES (?)', [JSON.stringify(game)]);
    await db.query('INSERT INTO settings(key,value) VALUES (?,?)', ['seeded', '1']);
  }
}

export function createStore(db) {
  return {
    async games() {
      const result = await db.query('SELECT * FROM games ORDER BY id DESC');
      return result.rows.map(row => ({ ...JSON.parse(row.body), id: Number(row.id) }));
    },
    async getGame(id) {
      const { rows } = await db.query('SELECT body FROM games WHERE id=?', [id]);
      return rows[0] ? { ...JSON.parse(rows[0].body), id } : null;
    },
    async saveGame(game, id) {
      if (id) {
        await db.query('UPDATE games SET body=? WHERE id=?', [JSON.stringify(game), id]);
        return id;
      }
      const { rows } = await db.query('INSERT INTO games(body) VALUES (?) RETURNING id', [JSON.stringify(game)]);
      return Number(rows[0].id);
    },
    async deleteGame(id) { await db.query('DELETE FROM games WHERE id=?', [id]); },
    async admin() {
      const password = process.env.ADMIN_PASSWORD;
      if (password !== undefined) {
        if (password.length < 12 || password.length > 256) throw new ConfigurationError('Configure ADMIN_PASSWORD com 12 a 256 caracteres na hospedagem.');
        const salt = 'henrique-store-environment-v1';
        return { salt, hash: scryptSync(password, salt, 64).toString('hex') };
      }
      if (process.env.VERCEL || remoteUrl()) throw new ConfigurationError('Defina ADMIN_PASSWORD nas variáveis de ambiente da Vercel e faça um novo deploy.');
      const { rows } = await db.query("SELECT value FROM settings WHERE key='admin'");
      return JSON.parse(rows[0].value);
    },
    async authenticated(token, adminHash) {
      if (!token || !/^[a-f0-9]{64}$/.test(token)) return false;
      const { rows } = await db.query('SELECT token FROM sessions WHERE token=? AND expires>? AND auth_hash=?', [hashToken(token), Date.now(), adminHash]);
      return rows.length > 0;
    },
    async login(adminHash) {
      const token = randomBytes(32).toString('hex');
      await db.query('DELETE FROM sessions WHERE expires<=?', [Date.now()]);
      await db.query('INSERT INTO sessions(token,expires,auth_hash) VALUES (?,?,?)', [hashToken(token), Date.now() + 28800000, adminHash]);
      return token;
    },
    async logout(token) { if (token) await db.query('DELETE FROM sessions WHERE token=?', [hashToken(token)]); },
    async attempt(ip) {
      const now = Date.now();
      await db.query('DELETE FROM login_attempts WHERE expires<=?', [now]);
      const { rows } = await db.query(`INSERT INTO login_attempts(ip,count,expires) VALUES (?,1,?)
        ON CONFLICT(ip) DO UPDATE SET count=login_attempts.count+1 RETURNING count`, [hashToken(ip), now + 900000]);
      return Number(rows[0].count);
    },
    async resetAttempts(ip) { await db.query('DELETE FROM login_attempts WHERE ip=?', [hashToken(ip)]); },
  };
}

let pending;
export function getStore() {
  if (!pending) pending = openStore().catch(error => { pending = undefined; throw error; });
  return pending;
}

async function openStore() {
  if (needsDatabase()) throw new ConfigurationError('Conecte um banco PostgreSQL ao projeto na Vercel, configure DATABASE_URL e faça um novo deploy.');
  let db;
  if (remoteUrl()) {
    const { Pool } = await import('pg');
    const pool = new Pool({ connectionString: remoteUrl(), max: 2, connectionTimeoutMillis: 8000, idleTimeoutMillis: 10000, allowExitOnIdle: true });
    pool.on('error', () => console.error('A conexão ociosa com PostgreSQL foi encerrada.'));
    try {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        // Serialize migrations and sample data across concurrent serverless instances.
        await client.query('SELECT pg_advisory_xact_lock(72148390)');
        await initializeDatabase({ kind: 'postgres', query: (sql, args = []) => client.query(postgresQuery(sql), args) });
        await client.query('COMMIT');
      } catch (error) { await client.query('ROLLBACK'); throw error; }
      finally { client.release(); }
    } catch (error) { await pool.end(); throw error; }
    db = { kind: 'postgres', query: (sql, args = []) => pool.query(postgresQuery(sql), args) };
  } else {
    // Filesystem writes and SQLite are only used outside Vercel.
    const { DatabaseSync } = await import('node:sqlite');
    const directory = process.env.DATA_DIR || path.join(root, 'data');
    mkdirSync(directory, { recursive: true });
    const sqlite = new DatabaseSync(path.join(directory, 'store.db'));
    sqlite.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
    db = { kind: 'sqlite', async query(sql, args = []) {
      const statement = sqlite.prepare(sql);
      if (statement.columns().length) return { rows: statement.all(...args) };
      return { rows: [], rowCount: Number(statement.run(...args).changes) };
    } };
    sqlite.exec('BEGIN IMMEDIATE');
    try {
      await initializeDatabase(db);
      if (!(await db.query("SELECT value FROM settings WHERE key='admin'")).rows.length) {
        const password = process.env.ADMIN_PASSWORD || randomBytes(15).toString('base64url');
        const salt = randomBytes(16).toString('hex');
        await db.query('INSERT INTO settings(key,value) VALUES (?,?)', ['admin', JSON.stringify({ salt, hash: scryptSync(password, salt, 64).toString('hex') })]);
        if (!process.env.ADMIN_PASSWORD) writeFileSync(path.join(directory, 'senha-admin.txt'), password, { mode: 0o600 });
      }
      sqlite.exec('COMMIT');
    } catch (error) { sqlite.exec('ROLLBACK'); sqlite.close(); throw error; }
  }
  return createStore(db);
}
